// sidenav model class
export class SideNavData {
  ID!: string;
  JSON_KEY!: string;
  Status!: string;
  URL!: string;
  imageName!: string;
  isEnable!: string;
  menuName!: string;
  rights!: string;
  sequenceNo!: string;
  textToDisplay!: string;
  type!: string;
  isSubMenuOpen!: boolean;
  subMenu?: SubMenu[];
}

export class SubMenu {
  appid?: number | string;
  createdby?: number | string;
  createdon?: number | string;
  enabled?: string;
  id?: number | string;
  jsonkey?: string;
  menuid?: number | string;
  menuimage?: string;
  menulogo?: string;
  pageurl?: string;
  rights?: string;
  seqdisplay?: number | string;
  statusid?: number | string;
  submenuname?: string;
  texttodisplay?: string;
}

export const SIDEMENU: SideNavData[] = [
  {
    Status: 'Active',
    imageName: 'dashboard.svg',
    sequenceNo: '1',
    rights: 'T',
    menuName: 'Dashboard',
    JSON_KEY: 'dashboard.svg',
    ID: '920',
    type: 'HAMBURGER',
    URL: 'dashboard',
    textToDisplay: 'null',
    isEnable: 'Y',
    isSubMenuOpen: false,
  },
  {
    Status: 'Active',
    imageName: 'my_account.svg',
    sequenceNo: '3',
    rights: 'T',
    menuName: 'Service 1',
    JSON_KEY: 'my_account.svg',
    ID: '9003',
    type: 'HAMBURGER',
    URL: 'service1',
    textToDisplay: 'null',
    isEnable: 'Y',
    isSubMenuOpen: false,
    subMenu: [
      {
        id: 139,
        menuimage: 'null',
        createdby: 1,
        createdon: 1634757237688,
        statusid: 3,
        texttodisplay: 'null',
        menuid: 9003,
        jsonkey: 'OPERATIVE_ACCOUNT',
        menulogo: 'null',
        appid: 5,
        submenuname: 'OPERATIVE_ACCOUNT',
        seqdisplay: 10,
        rights: 'T',
        pageurl: 'myAccount',
        enabled: 'Y',
      },
      {
        id: 142,
        menuimage: 'null',
        createdby: 1,
        createdon: 1634757237688,
        statusid: 3,
        texttodisplay: 'null',
        menuid: 9003,
        jsonkey: 'MY_DEPOSITS',
        menulogo: 'null',
        appid: 5,
        submenuname: 'MY_DEPOSITS',
        seqdisplay: 10,
        rights: 'T',
        pageurl: 'myDeposits',
        enabled: 'Y',
      },
      {
        id: 150,
        menuimage: 'null',
        createdby: 1,
        createdon: 1634757237688,
        statusid: 3,
        texttodisplay: 'null',
        menuid: 9003,
        jsonkey: 'MY_TERM_LOANS',
        menulogo: 'null',
        appid: 5,
        submenuname: 'MY_TERM_LOANS',
        seqdisplay: 10,
        rights: 'T',
        pageurl: 'myLoans',
        enabled: 'Y',
      },
    ],
  },
  {
    Status: 'Active',
    subMenu: [
      {
        id: 139,
        menuimage: 'null',
        createdby: 1,
        createdon: 1634757237688,
        statusid: 3,
        texttodisplay: 'null',
        menuid: 9003,
        jsonkey: 'INSTANT_PAY',
        menulogo: 'null',
        appid: 5,
        submenuname: 'INSTANT_PAY',
        seqdisplay: 10,
        rights: 'T',
        pageurl: 'instantPay',
        enabled: 'Y',
      },
      {
        id: 142,
        menuimage: 'null',
        createdby: 1,
        createdon: 1634757237688,
        statusid: 3,
        texttodisplay: 'null',
        menuid: 9003,
        jsonkey: 'MANAGE_PAYEE',
        menulogo: 'null',
        appid: 5,
        submenuname: 'MANAGE_PAYEE',
        seqdisplay: 10,
        rights: 'T',
        pageurl: 'managePayee',
        enabled: 'Y',
      },
      {
        id: 150,
        menuimage: 'null',
        createdby: 1,
        createdon: 1634757237688,
        statusid: 3,
        texttodisplay: 'null',
        menuid: 9003,
        jsonkey: 'SEND_MONEY',
        menulogo: 'null',
        appid: 5,
        submenuname: 'SEND_MONEY',
        seqdisplay: 10,
        rights: 'T',
        pageurl: 'sendMoney',
        enabled: 'Y',
      },
      {
        id: 151,
        menuimage: 'null',
        createdby: 1,
        createdon: 1634757237688,
        statusid: 3,
        texttodisplay: 'null',
        menuid: 9003,
        jsonkey: 'STANDING_INSTRUCTION',
        menulogo: 'null',
        appid: 5,
        submenuname: 'STANDING_INSTRUCTION',
        seqdisplay: 10,
        rights: 'T',
        pageurl: 'standingInstructionList',
        enabled: 'Y',
      },
      {
        id: 153,
        menuimage: 'null',
        createdby: 1,
        createdon: 1634757237688,
        statusid: 3,
        texttodisplay: 'null',
        menuid: 9003,
        jsonkey: 'Scheduled Transaction',
        menulogo: 'null',
        appid: 5,
        submenuname: 'Scheduled Transaction',
        seqdisplay: 10,
        rights: 'T',
        pageurl: 'transactionStatus',
        enabled: 'Y',
      },
    ],
    imageName: 'send_money.svg',
    sequenceNo: '3',
    rights: 'T',
    menuName: 'Service 2',
    JSON_KEY: 'send_money.svg',
    ID: '9003',
    type: 'HAMBURGER',
    URL: 'service2',
    textToDisplay: 'null',
    isEnable: 'Y',
    isSubMenuOpen: false,
  },
  {
    Status: 'Active',
    subMenu: [
      {
        id: 130,
        menuimage: 'null',
        createdby: 1,
        createdon: 1640632437688,
        statusid: 3,
        texttodisplay: 'null',
        menuid: 9004,
        jsonkey: 'APPLY_FOR_NEW_CARD',
        menulogo: 'null',
        appid: 5,
        submenuname: 'APPLY_FOR_NEW_CARD',
        seqdisplay: 10,
        rights: 'T',
        pageurl: 'applyCards',
        enabled: 'Y',
      },
      {
        id: 136,
        menuimage: 'null',
        createdby: 1,
        createdon: 1640632437688,
        statusid: 3,
        texttodisplay: 'null',
        menuid: 9004,
        jsonkey: 'DEBIT_CARDS',
        menulogo: 'null',
        appid: 5,
        submenuname: 'DEBIT_CARDS',
        seqdisplay: 10,
        rights: 'T',
        pageurl: 'debitCards',
        enabled: 'Y',
      },
    ],
    imageName: 'cards.svg',
    sequenceNo: '3',
    rights: 'T',
    menuName: 'Service 3',
    JSON_KEY: 'cards.svg',
    ID: '9004',
    type: 'HAMBURGER',
    URL: 'service3',
    textToDisplay: 'null',
    isEnable: 'Y',
    isSubMenuOpen: false,
  },
  {
    Status: 'Active',
    sequenceNo: '3',
    imageName: 'dashboard.svg',
    menuName: 'Service 4',
    rights: 'T',
    ID: '987',
    JSON_KEY: 'billpay.svg',
    type: 'menu',
    URL: 'service4',
    textToDisplay: 'null',
    isEnable: 'Y',
    isSubMenuOpen: false,
    subMenu: [
      {
        id: '20',
        statusid: '08',
        submenuname: 'BILL_PAYMENT',
        pageurl: 'retailRechargeBillPay',
      },
      {
        id: 'Active',
        statusid: '08',
        submenuname: 'REGISTERED_PAY',
        pageurl: 'registerBillerView',
      },
      {
        id: 'Active',
        statusid: '08',
        submenuname: 'REMINDER_LIST',
        pageurl: 'billReminderList',
      },
      {
        id: 'Active',
        statusid: '08',
        submenuname: 'COMPLAINT',
        pageurl: 'complaintList',
      },
      {
        id: 'Active',
        statusid: '08',
        submenuname: 'PAYMENT_HISTORY',
        pageurl: 'retailPaymentHistory',
      },
    ],
  },
  {
    Status: 'Active',
    subMenu: [
      {
        id: 137,
        menuimage: 'null',
        createdby: 1,
        createdon: 1634757237688,
        statusid: 3,
        texttodisplay: 'null',
        menuid: 9007,
        jsonkey: 'DELINK_ACCOUNT',
        menulogo: 'null',
        appid: 5,
        submenuname: 'DELINK_ACCOUNT',
        seqdisplay: 2,
        rights: 'T',
        pageurl: 'delinkAccount',
        enabled: 'Y',
      },
      {
        id: 138,
        menuimage: 'null',
        createdby: 1,
        createdon: 1634757237688,
        statusid: 3,
        texttodisplay: 'null',
        menuid: 9007,
        jsonkey: 'FREEZE_ACCOUNTS',
        menulogo: 'null',
        appid: 5,
        submenuname: 'FREEZE_ACCOUNTS',
        seqdisplay: 4,
        rights: 'T',
        pageurl: 'freezeAccount',
        enabled: 'Y',
      },
      {
        id: 141,
        menuimage: 'null',
        createdby: 1,
        createdon: 1634757237688,
        statusid: 3,
        texttodisplay: 'null',
        menuid: 9007,
        jsonkey: 'LINK_ACCOUNT',
        menulogo: 'null',
        appid: 5,
        submenuname: 'LINK_ACCOUNT',
        seqdisplay: 1,
        rights: 'T',
        pageurl: 'linkAccount',
        enabled: 'Y',
      },
      {
        id: 154,
        menuimage: 'null',
        createdby: 1,
        createdon: 1634757237688,
        statusid: 3,
        texttodisplay: 'null',
        menuid: 9007,
        jsonkey: 'TDS_CERTIFICATE',
        menulogo: 'null',
        appid: 5,
        submenuname: 'TDS_CERTIFICATE',
        seqdisplay: 3,
        rights: 'V',
        pageurl: 'tdsCertificate',
        enabled: 'Y',
      },
    ],
    imageName: 'cheque.svg',
    sequenceNo: '6',
    rights: 'T',
    menuName: 'Service 5',
    JSON_KEY: 'cheque.svg',
    ID: '9007',
    type: 'HAMBURGER',
    URL: 'service5',
    textToDisplay: 'null',
    isEnable: 'Y',
    isSubMenuOpen: false,
  },

  {
    Status: 'Active',
    imageName: 'send_money.svg',
    sequenceNo: '8',
    rights: 'T',
    menuName: 'Service 6',
    JSON_KEY: 'send_money.svg',
    ID: '9009',
    type: 'HAMBURGER',
    URL: 'service6',
    textToDisplay: 'null',
    isEnable: 'Y',
    isSubMenuOpen: false,
  },
  {
    Status: 'Active',
    subMenu: [
      {
        id: 143,
        menuimage: 'null',
        createdby: 1,
        createdon: 1634757237688,
        statusid: 3,
        texttodisplay: 'null',
        menuid: 9010,
        jsonkey: 'MY_CHEQUE_BOOK',
        menulogo: 'null',
        appid: 5,
        submenuname: 'MY_CHEQUE_BOOK',
        seqdisplay: 1,
        rights: 'V',
        pageurl: 'myChequeBook',
        enabled: 'Y',
      },
      {
        id: 134,
        menuimage: 'null',
        createdby: 1,
        createdon: 1634757237688,
        statusid: 3,
        texttodisplay: 'null',
        menuid: 9010,
        jsonkey: 'CHEQUE_STATUS_ENQUIRY',
        menulogo: 'null',
        appid: 5,
        submenuname: 'CHEQUE_STATUS_ENQUIRY',
        seqdisplay: 5,
        rights: 'V',
        pageurl: 'chequeStatusEnquiry',
        enabled: 'Y',
      },
      {
        id: 147,
        menuimage: 'null',
        createdby: 1,
        createdon: 1634757237688,
        statusid: 3,
        texttodisplay: 'null',
        menuid: 9010,
        jsonkey: 'POSITIVE_PAY',
        menulogo: 'null',
        appid: 5,
        submenuname: 'POSITIVE_PAY',
        seqdisplay: 4,
        rights: 'T',
        pageurl: 'positivePay',
        enabled: 'Y',
      },
      {
        id: 152,
        menuimage: 'null',
        createdby: 1,
        createdon: 1634757237688,
        statusid: 3,
        texttodisplay: 'null',
        menuid: 9010,
        jsonkey: 'STOP_CHEQUE',
        menulogo: 'null',
        appid: 5,
        submenuname: 'STOP_CHEQUE',
        seqdisplay: 3,
        rights: 'T',
        pageurl: 'stopCheques',
        enabled: 'Y',
      },
      {
        id: 140,
        menuimage: 'null',
        createdby: 1,
        createdon: 1634757237688,
        statusid: 3,
        texttodisplay: 'null',
        menuid: 9010,
        jsonkey: 'INWARD_CHEQUE_ENQUIRY',
        menulogo: 'null',
        appid: 5,
        submenuname: 'INWARD_CHEQUE_ENQUIRY',
        seqdisplay: 6,
        rights: 'V',
        pageurl: 'inwardChequeInquiry',
        enabled: 'Y',
      },
      {
        id: 144,
        menuimage: 'null',
        createdby: 1,
        createdon: 1634757237688,
        statusid: 3,
        texttodisplay: 'null',
        menuid: 9010,
        jsonkey: 'NEW_CHEQUEBOOK_REQUEST',
        menulogo: 'null',
        appid: 5,
        submenuname: 'NEW_CHEQUEBOOK_REQUEST',
        seqdisplay: 2,
        rights: 'T',
        pageurl: 'chequeBookRequest',
        enabled: 'Y',
      },
    ],
    imageName: 'cheque.svg',
    sequenceNo: '9',
    rights: 'T',
    menuName: 'Service 7',
    JSON_KEY: 'cheque.svg',
    ID: '9010',
    type: 'HAMBURGER',
    URL: 'service7',
    textToDisplay: 'null',
    isEnable: 'Y',
    isSubMenuOpen: false,
  },
];
//detailstatementitem model class
export class DetailStatementItem {
  TransactionDate!: string;
  particulars!: string;
  TransactionId!: string;
  instrumentNumber!: string;
  creditOrDebit!: 'D' | 'C';
  amount!: number;
  closingBalance!: number;
}

export const DETAILSTATEMENTITEM: DetailStatementItem[] = [
  {
    TransactionDate: '20230825',
    particulars: 'Transaction 1',
    TransactionId: '123',
    instrumentNumber: '456',
    creditOrDebit: 'D',
    amount: 100,
    closingBalance: 500,
  },
  {
    TransactionDate: '20230826',
    particulars: 'Transaction 2',
    TransactionId: '124',
    instrumentNumber: '457',
    creditOrDebit: 'C',
    amount: 50,
    closingBalance: 450,
  },
];
